export const PRODUCT_LIST = "PRODUCT_LIST";
export const PRODUCT_SEARCH_LIST = "PRODUCT_SEARCH_LIST";
export const PRODUCT_STORE_LIST = "PRODUCT_STORE_LIST";
export const PRODUCT_DETAIL = "PRODUCT_DETAIL";

export const PRODUCT_QUANTITY_STATISTIC = "PRODUCT_QUANTITY_STATISTIC";