export const CUSTOMER_LIST = "CUSTOMER_LIST";
export const CUSTOMER_DETAIL = "CUSTOMER_DETAIL";
// statistics
export const CUSTOMER_PURCHASE_STATISTIC = "CUSTOMER_PURCHASE_STATISTIC";
export const CUSTOMER_PURCHASE_QUANTITY_STATISTIC = "CUSTOMER_PURCHASE_QUANTITY_STATISTIC";