export const ORDER_STATISTIC_YEAR = "ORDER_STATISTIC_YEAR";
export const ORDER_STATISTIC_FILTER = "ORDER_STATISTIC_FILTER";
export const ORDER_STATISTIC_REVENUE = "ORDER_STATISTIC_REVENUE";
export const ORDER_STATISTIC_SUCCESS_RATE = "ORDER_STATISTIC_SUCCESS_RATE";